/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio12;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;


/**
 *
 * @author Leonardo
 */
public class JFramePrincipal extends javax.swing.JFrame {

     DefaultListModel<String> historialModel = new DefaultListModel<>();
    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        lstHistorial.setModel(historialModel);
        
        
        //---------------------------BOTONES DE LAS OPERACIONES-----------------------------------------------------------------------------
        btnSuma.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                calcular("+");
            }
        });

        btnResta.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                calcular("-");
            }
        });

        btnMultiplicacion.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                calcular("*");
            }
        });

        btnDivision.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                calcular("/");
            }
        });
        btnPotencia.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                 calcular("^"); // Llamada al método de cálculo con el operador "^"
              }
        });
        
        //------------------------------------------------------------------------------------------------------------------------------------------------------
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSuma = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        txtNum02 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnResta = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNum01 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstHistorial = new javax.swing.JList<>();
        btnPotencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab12Recursos/Group 1 (4).png"))); // NOI18N
        btnSuma.setBorder(null);
        btnSuma.setContentAreaFilled(false);
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        btnMultiplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab12Recursos/Group 2 (5).png"))); // NOI18N
        btnMultiplicacion.setBorder(null);
        btnMultiplicacion.setContentAreaFilled(false);
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        txtNum02.setBackground(new java.awt.Color(255, 255, 255));
        txtNum02.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNum02.setBorder(null);
        jPanel1.add(txtNum02, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 140, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab12Recursos/Rectangle 7.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        btnResta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab12Recursos/Group 3 (4).png"))); // NOI18N
        btnResta.setBorder(null);
        btnResta.setContentAreaFilled(false);
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        jPanel1.add(btnResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        btnDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab12Recursos/Group 4 (3).png"))); // NOI18N
        btnDivision.setBorder(null);
        btnDivision.setContentAreaFilled(false);
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        jPanel1.add(btnDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        txtResultado.setBackground(new java.awt.Color(255, 255, 255));
        txtResultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtResultado.setBorder(null);
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 90, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab12Recursos/Group 5 (3).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab12Recursos/Rectangle 8.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        txtNum01.setBackground(new java.awt.Color(255, 255, 255));
        txtNum01.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNum01.setBorder(null);
        jPanel1.add(txtNum01, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 150, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab12Recursos/Rectangle 7.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jScrollPane1.setBorder(null);

        lstHistorial.setBackground(new java.awt.Color(255, 255, 255));
        lstHistorial.setBorder(null);
        lstHistorial.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lstHistorial.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(lstHistorial);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 360));

        btnPotencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab12Recursos/Group 7 (1).png"))); // NOI18N
        btnPotencia.setBorder(null);
        btnPotencia.setContentAreaFilled(false);
        btnPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotenciaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPotencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    
    
    
    
    //---------------------------BOTONES DE LAS OPERACIONES---------------------------------------------------------------------------------
    
    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed

    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed

    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed

    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed

    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPotenciaActionPerformed

    //---------OPERACION CALCULAR----------------------------------------------------------------------------------------------------------------
    
    private void calcular(String operacion){
        try {
        double num1 = Double.parseDouble(txtNum01.getText());
        double num2 = Double.parseDouble(txtNum02.getText());
        double resultado = 0;

        switch (operacion) {
            case "+":
                resultado = num1 + num2;
                break;
            case "-":
                resultado = num1 - num2;
                break;
            case "*":
                resultado = num1 * num2;
                break;
            case "/":
                if (num2 != 0) {
                    resultado = num1 / num2;
                } else {
                    JOptionPane.showMessageDialog(this, "No se puede dividir por cero");
                }
                break;
             case "^":
                resultado = Math.pow(num1, num2); // Cálculo de la potencia
                break;
        }

        txtResultado.setText(String.valueOf(resultado));

        // Agregar la operación y el resultado al historial
        String historial = num1 + "    " + operacion + "    " + num2 + "    =    " + resultado;
        historialModel.addElement(historial);
         } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingresa números válidos");
    }
    }
       //--------------------------------------------------------------------------------------------------------------------------------------------------------
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnPotencia;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstHistorial;
    private javax.swing.JTextField txtNum01;
    private javax.swing.JTextField txtNum02;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
